# -*- generated by 1.0.9 -*-
import da
_config_object = {}
from Crypto.PublicKey import RSA
from Crypto import Random

class Olympus(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])
